// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/whalerapi/templ-go/models"

func AllPostsPage(posts []models.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4\"><img src=\"/static/whalerapi.png\" alt=\"Blog Hero Image\" class=\"w-full h-64 object-cover rounded-lg mb-8\"><h1 class=\"text-4xl font-bold my-8\">Blog Archive</h1><p class=\"text-lg opacity-90 mb-8\">A List of All Blog Posts</p><div class=\"mb-8\"><input type=\"text\" placeholder=\"Search posts...\" class=\"border border-gray-300 rounded-lg py-2 px-4 w-full\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(posts) == 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p>No posts found.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"grid grid-cols-1 md:grid-cols-2 gap-8\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, post := range posts {
					templ_7745c5c3_Err = PostCard(post).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("All Posts").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Here is another version with horizontal cards and a small hero section
// The images for the cards need to be added to the Post model as ImageURL

// templ AllPostsPage(posts []models.Post) {
//     @Layout("All Posts") {
//         // --- Smaller Hero Section ---
//         <div class="bg-gradient-to-r from-blue-600 to-teal-500 py-12 text-white">
//             <div class="container mx-auto px-4 text-center">
//                 <h1 class="text-4xl font-bold">Blog Archive</h1>
//                 <p class="text-lg opacity-90 mt-2">Our latest thoughts on technology and development.</p>
//             </div>
//         </div>

//         // --- Two-Column Content Area ---
//         <div class="container mx-auto px-4 py-12">
//             if len(posts) == 0 {
//                 <p class="text-center text-gray-600">No posts found.</p>
//             } else {
//                 // --- Grid for Horizontal Cards ---
//                 <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
//                     for _, post := range posts {
//                         // --- Horizontal Card ---
//                         <div class="bg-white rounded-lg shadow-md overflow-hidden flex flex-col md:flex-row transition-shadow duration-300 hover:shadow-xl">
//                             // Image Section
//                             <div class="md:w-1/3 flex-shrink-0">
//                                 // Use post.ImageURL here. Using a placeholder for now.
//                                 <img src="https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=60" alt={ post.Title } class="h-48 w-full object-cover md:h-full"/>
//                             </div>

//	                            // Text Content Section
//	                            <div class="p-6 flex flex-col flex-grow">
//	                                <div>
//	                                    <h2 class="text-xl font-semibold mb-2">
//	                                        <a href={ templ.URL("/blog/" + post.Slug) } class="hover:underline text-blue-700">
//	                                            { post.Title }
//	                                        </a>
//	                                    </h2>
//	                                    <p class="text-gray-600 text-sm mb-4 line-clamp-3">{ post.Summary }</p>
//	                                </div>
//	                                <div class="mt-auto">
//	                                    <a href={ templ.URL("/blog/" + post.Slug) } class="text-blue-600 hover:text-blue-800 font-semibold text-sm">
//	                                        Read More &rarr;
//	                                    </a>
//	                                </div>
//	                            </div>
//	                        </div>
//	                    }
//	                </div>
//	            }
//	        </div>
//	    }
//	}
var _ = templruntime.GeneratedTemplate
