// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/whalelogic/templ-go/models"

func IndexPage(posts []models.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white/60 backdrop-blur-lg rounded-2xl shadow-lg border border-slate-200 overflow-hidden\"><div class=\"md:flex\"><div class=\"md:flex-shrink-0 p-8 flex items-center justify-center\"><div class=\"flex items-center justify-center\"><img class=\"w-48 h-48 border-4 rounded-2xl border-white drop-shadow-xl\" src=\"/static/whaletail-whalelogic.png\" alt=\"Profile Picture\"></div></div><div class=\"p-8\"><div class=\"tracking-wide text-sm text-indigo-600 font-bold\">Cloud Developer</div><h1 class=\"mt-1 text-3xl font-bold text-slate-900\">Keith Thomson</h1><p class=\"mt-2 text-slate-600\">Engineering Cloud Solutions for Tomorrow. I document my projects, code, and architecture patterns, as well as promote my business, <em><b>WhaleLogic</b></em> - a cloud-native software development company.</p><div class=\"mt-4 flex items-center gap-4\"><a href=\"https://www.github.com/whalelogic\" class=\"inline-flex items-center gap-2 text-slate-600 hover:text-indigo-800 transition-colors\"><img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg\" alt=\"GitHub\" class=\"h-6 w-6\"></a> <a href=\"https://www.linkedin.com/in/keith-thomson-a2399923/\" class=\"inline-flex items-center gap-2 text-slate-600 hover:text-indigo-800 transition-colors\"><img src=\"https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/linkedin/linkedin-original.svg\" alt=\"LinkedIn\" class=\"h-6 w-6\"></a></div></div></div></div><h2 class=\"text-3xl font-bold mt-16 mb-8 text-slate-900\">Content</h2><div class=\"grid grid-cols-1 md:grid-cols-2 gap-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, post := range posts {
				templ_7745c5c3_Err = PostCard(post).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("TerraInCloudnito").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
