// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/whalerapi/templ-go/models"
import "strings"

func getIconForCategory(category string) string {
	// Normalize category name for filename matching
	lowerCategory := strings.ToLower(category)
	switch {
	case strings.Contains(lowerCategory, "python"):
		return "/static/python.png"
	case strings.Contains(lowerCategory, "go"), strings.Contains(lowerCategory, "golang"):
		return "/static/golang.svg"
	case strings.Contains(lowerCategory, "rust"):
		return "/static/rust.png"
	case strings.Contains(lowerCategory, "http"):
		return "/static/http.png"
	case strings.Contains(lowerCategory, "api"):
		return "/static/rest-api.png"
	case strings.Contains(lowerCategory, "javascript"), strings.Contains(lowerCategory, "js"):
		return "/static/javascript.svg"
	case strings.Contains(lowerCategory, "data"):
		return "/static/mariadb.svg"
	case strings.Contains(lowerCategory, "ethics"), strings.Contains(lowerCategory, "ai"):
		return "/static/ethics.png"
	case strings.Contains(lowerCategory, "google"), strings.Contains(lowerCategory, "gcp"):
		return "/static/google-cloud.svg"
	case strings.Contains(lowerCategory, "docker"):
		return "/static/docker.svg"
	case strings.Contains(lowerCategory, "kubernetes"), strings.Contains(lowerCategory, "k8s"):
		return "/static/kubernetes.svg"
	case strings.Contains(lowerCategory, "aws"), strings.Contains(lowerCategory, "amazon"):
		return "/static/aws.svg"
	case strings.Contains(lowerCategory, "flask"):
		return "/static/flask.svg"
	case strings.Contains(lowerCategory, "fiber"):
		return "/static/fiber.svg"
	case strings.Contains(lowerCategory, "regex"), strings.Contains(lowerCategory, "regexp"):
		return "/static/regex.svg"
	case strings.Contains(lowerCategory, "html"):
		return "/static/html5.svg"
	case strings.Contains(lowerCategory, "css"):
		return "/static/css3.svg"
	case strings.Contains(lowerCategory, "philosophy"):
		return "/static/socrates-gopher.png"
	default:
		return "/static/rest-api.png" // A good default
	}
}

func PostCard(post models.Post) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.URL("/blog/" + post.Slug))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/post_card.templ`, Line: 52, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"group bg-white p-6 rounded-2xl shadow-md hover:shadow-xl transition-all duration-300 border border-slate-200 flex items-start space-x-6 hover:scale-105 hover:border-indigo-400\"><img src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(getIconForCategory(post.Category))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/post_card.templ`, Line: 53, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" alt=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(post.Category)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/post_card.templ`, Line: 53, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"h-12 w-12 flex-shrink-0 opacity-70 group-hover:opacity-100 transition-opacity duration-300\"><div class=\"flex-grow\"><h3 class=\"text-xl font-bold text-slate-900 group-hover:text-indigo-600 transition-colors duration-300\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(post.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/post_card.templ`, Line: 55, Col: 119}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</h3><p class=\"text-slate-600 mt-2 text-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(post.Summary)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/post_card.templ`, Line: 56, Col: 56}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</p></div></a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
